### ISSUE TITLE
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:47, unhandled cuda error, NCCL version 21.0.3 ncclUnhandledCudaError: Call to CUDA function failed

### ISSUE THREAD

**Issue by YXtrees** [YijinHuang/SSiT#19]
warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "main.py", line 140, in <module>
    main()
  File "main.py", line 85, in main
    mp.spawn(worker, nprocs=n_gpus, args=(n_gpus, args))
  File "/usr/local/miniconda3/envs/ssit/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/miniconda3/envs/ssit/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/usr/local/miniconda3/envs/ssit/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/ssit/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/hy-tmp/SSiT/main.py", line 102, in worker
    torch.distributed.barrier()
  File "/usr/local/miniconda3/envs/ssit/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2776, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:47, unhandled cuda error, NCCL version 21.0.3
ncclUnhandledCudaError: Call to CUDA function failed. 请问总是报这种错误，应该怎么解决

**Comment by YijinHuang** [comment]
你好，这个可能是CUDA版本和pytorch版本不兼容导致的。这个项目之前是torch版本是1.11的，对应的CUDA版本是11.3。

**Comment by YXtrees** [comment]
感谢您的回复，我已经解决问题
